services:
  db:
    image: postgres:16-alpine  # Versão do Postgres
    container_name: meu-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres       # Usuário (mude se necessário)
      POSTGRES_PASSWORD: admin   # Senha (mude se necessário)
      POSTGRES_DB: horafit     # Nome do banco de dados
    ports:
      - "5433:5432"              # Porta local isolada para não conflitar com outros projetos
    volumes:
      - postgres_data:/var/lib/postgresql/data # Salva os dados para não perder

volumes:
  postgres_data:
